version: "3"  # optional since v1.27.0
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_HOST_URL=http://localhost:5000
    image: client1
    container_name: client2
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app/
    # environment:
    stdin_open: true
    tty: true
    links: 
      - be
  be:
    build: .
    image: backend1
    container_name: backend2
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    environment:
      - DB_PW=
      - DB_NAME=Review
      - DB_USER=
      - JWT_SECRET=
    
  # volumes:
  #   db-data:








